server:
  port: ${SERVER_PORT:8085}

spring:
  application:
    name: envios_api
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none   # opciones: none | validate | update | create | create-drop
  mvc:
    contentnegotiation:
      favor-parameter: false
      favor-path-extension: false
      media-types:
        json: application/json
    default-content-type: application/json
  jackson:
    serialization:
      indent_output: true     # para ver el JSON bonito en desarrollo
    default-property-inclusion: non_null  # ignora campos nulos
  jwt:
    secret: ${JWT_SECRET}
    algorithm: HS256