server:
  port: ${SERVER_PORT:8080}

springdoc:
  swagger-ui:
    # Cuando no usas query param, puedes listar URLs:
    # urls:
    #  - name: "Microservicios"
    #    url: /api-docs
    path: /swagger-ui/index.html

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway_api
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: catalogo_api
              uri: http://host.docker.internal:8081
              predicates:
                - Path=/api/productos/**
            - id: pedidos_api
              uri: http://host.docker.internal:8082
              predicates:
                - Path=/api/productos/**
            - id: pagos_api
              uri: http://host.docker.internal:8083
              predicates:
                - Path=/api/productos/**
            - id: inventario_api
              uri: http://host.docker.internal:8084
              predicates:
                - Path=/api/productos/**
            - id: envios_api
              uri: http://host.docker.internal:8085
              predicates:
                - Path=/api/productos/**
            - id: notificaciones_api
              uri: http://host.docker.internal:8086
              predicates:
                - Path=/api/productos/**